/**
 * Base API URL resolver.
 * In local dev (Vite), relative URLs ('/api/...') are proxied to http://localhost:5000 via vite.config.js.
 * In production, set VITE_API_URL in your environment (e.g. on Vercel) to point to your cloud backend
 * (e.g. 'https://asterix-backend.onrender.com'), or configure vercel.json rewrites.
 */
export const API_BASE = (
    import.meta.env.VITE_API_URL || (import.meta.env.PROD ? 'https://asterix-backend.onrender.com' : '')
).replace(/\/+$/, '');

/* Paths served by the frontend itself, not by the API. Everything in public/
   lands here. Prefixing these with API_BASE sends them to the backend origin,
   which has no such files and answers 404 -- so they are returned untouched. */
const FRONTEND_PATHS = /^\/(gallery|intro|assets|icons\.svg|favicon\.|asterix-logo)/i;

/* Records written while the server had no ImageKit credentials point at files
   saved on the Render container's own disk, which is erased by every deploy.
   Those URLs are dead for good, so they are blanked here and the component's
   own fallback (initials, placeholder art) is shown instead of a broken image.

   Deliberately matched by host rather than by the '/uploads/' path: a server
   with a persistent volume mounted at UPLOADS_DIR serves that path perfectly
   well, and this must not blank it. Remove this once the affected records have
   been re-uploaded to the CDN. */
const DEAD_UPLOAD_HOST = /^https?:\/\/asterix-backend\.onrender\.com\/uploads\//i;

/* Records written before the gallery moved to the CDN hold build output paths
   like '/assets/06_team_celebration-DWYblmDj.jpg'. The hash in that name is
   regenerated by every production build, so the file it names stopped existing
   the moment the site was rebuilt. The same pictures ship unhashed in
   public/gallery, so those paths are rewritten to the copy that stays put. */
const HASHED_BUILD_ASSET = /^\/assets\/(.+)-[A-Za-z0-9_-]{8}(\.[a-z0-9]+)$/i;

export function apiUrl(path) {
    if (!path || typeof path !== 'string') return '';
    const trimmed = path.trim();
    if (!trimmed) return '';

    // Legacy links to files that no longer exist on the backend's disk.
    if (DEAD_UPLOAD_HOST.test(trimmed)) {
        return '';
    }
    if (
        trimmed.startsWith('http://') ||
        trimmed.startsWith('https://') ||
        trimmed.startsWith('data:') ||
        trimmed.startsWith('blob:')
    ) {
        return trimmed;
    }

    const cleanPath = trimmed.startsWith('/') ? trimmed : `/${trimmed}`;

    const hashed = cleanPath.match(HASHED_BUILD_ASSET);
    if (hashed) {
        return `/gallery/${hashed[1]}${hashed[2]}`;
    }

    // Static files shipped with the frontend resolve against the current origin.
    if (FRONTEND_PATHS.test(cleanPath)) {
        return cleanPath;
    }

    return API_BASE ? `${API_BASE}${cleanPath}` : cleanPath;
}
